### ISSUE TITLE
Second endpoint and database schema for aggregated events

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lassie-event-recorder#28]
# Goals

Add a new endpoint to record aggregated events to a new DB schema. 

The aggregated event in https://github.com/filecoin-project/lassie/pull/138 has the schema:

```
type AggregateEvent struct {
	InstanceID        string    `json:"instanceId"`                  // The ID of the Lassie instance generating the event
	RetrievalID       string    `json:"retrievalId"`                 // The unique ID of the retrieval
	StorageProviderID string    `json:"storageProviderId,omitempty"` // The ID of the storage provider that served the retrieval content
	TimeToFirstByte   int64     `json:"timeToFirstByte,omitempty"`   // The time it took to receive the first byte in milliseconds
	Bandwidth         uint64    `json:"bandwidth,omitempty"`         // The bandwidth of the retrieval in bytes per second
	Success           bool      `json:"success"`                     // Wether or not the retreival ended with a success event
	StartTime         time.Time `json:"startTime"`                   // The time the retrieval started
	EndTime           time.Time `json:"endTime"`                     // The time the retrieval ended
}
```

We need a new DB table and endpoint to absorb these events as well as feed them to metrics.

Will also need to expand upon in seperate ticket once https://github.com/filecoin-project/lassie/issues/152 is done to completely replace the original endpoint.

# Implementation

This seems like a good time to pull the HTTP server part out of the existing event reporter so it just focuses on handling the events, as opposed to handling http logic. And then the server can delegated aggregated handling to a different struct.

**Comment by kylehuntsman** [comment]
Closed by #29
