### ISSUE TITLE
Complete event recorder metrics for aggregated events

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/lassie-event-recorder#35]
# Goals

After https://github.com/filecoin-project/lassie/pull/167 was merged, we need to:
1. improve the DB schema and event recorder to record the expanded events
2. pass aggregated events into metrics
3. Verify aggregated events generate the same metrics as old events

**Comment by kylehuntsman** [comment]
Closing via the merge of https://github.com/filecoin-project/lassie/pull/236
